import { useCallback, useEffect, useRef, useState } from 'react';
import { FileText, Copy, Download, X } from 'lucide-react';
import { useStream } from '../../hooks/useStream';

interface RCAModalProps {
  sessionId: string;
  onClose: () => void;
}

export function RCAModal({ sessionId, onClose }: RCAModalProps) {
  const [content, setContent] = useState('');
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');
  const contentRef = useRef('');

  const onChunk = useCallback((chunk: string) => {
    contentRef.current += chunk;
    setContent(contentRef.current);
  }, []);
  const onDone = useCallback(() => setLoading(false), []);
  const onError = useCallback((e: string) => { setError(e); setLoading(false); }, []);

  const { start } = useStream('/api/diagnose/rca', { onChunk, onDone, onError });

  useEffect(() => {
    start({ diagnosis_id: sessionId, user_name: 'SRE Team' });
  }, []); // eslint-disable-line

  const download = () => {
    const date = new Date().toISOString().slice(0, 10);
    const body = content
      .replace(/^### (.+)$/gm, '<h3>$1</h3>')
      .replace(/^## (.+)$/gm, '<h2>$1</h2>')
      .replace(/^# (.+)$/gm, '<h2>$1</h2>')
      .replace(/\*\*(.+?)\*\*/g, '<strong>$1</strong>')
      .replace(/`([^`]+)`/g, '<code>$1</code>')
      .replace(/```[\w]*\n?([\s\S]+?)```/g, '<pre>$1</pre>')
      .replace(/^- (.+)$/gm, '<li>$1</li>')
      .replace(/(<li>[\s\S]+?<\/li>)(?!\s*<li>)/g, '<ul>$1</ul>')
      .replace(/\n{2,}/g, '</p><p>')
      .replace(/^(?!<[hup])/gm, '<p>')
      .replace(/(?<![>])$/gm, '</p>')
      .replace(/<p><\/p>/g, '');

    const html = `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8"/>
<title>RCA Report — ${date}</title>
<style>
  *{box-sizing:border-box;margin:0;padding:0}
  body{font-family:'Segoe UI',Arial,sans-serif;font-size:13px;color:#1a1a2e;background:#fff;padding:40px 52px;max-width:860px;margin:auto}
  h1{font-size:20px;font-weight:700;margin-bottom:4px}
  .meta{font-size:11px;color:#888;margin-bottom:28px}
  h2{font-size:14px;font-weight:700;color:#3b3b6e;margin:22px 0 6px;border-bottom:1px solid #e0e0f0;padding-bottom:4px}
  h3{font-size:13px;font-weight:700;color:#4b4b8e;margin:14px 0 4px}
  p,li{font-size:13px;line-height:1.75;color:#333;margin-bottom:6px}
  ul{padding-left:20px;margin-bottom:8px}
  pre,code{background:#f4f4f8;border:1px solid #dde;border-radius:4px;font-family:'JetBrains Mono','Courier New',monospace;font-size:11.5px;padding:10px 14px;white-space:pre-wrap;word-break:break-word;margin:6px 0 10px}
  .footer{margin-top:40px;font-size:10px;color:#aaa;text-align:center}
  @media print{body{padding:20px 24px}}
</style>
</head>
<body>
<h1>Root Cause Analysis Report</h1>
<p class="meta">Generated ${date} · Session ${sessionId.slice(0, 8)}</p>
${body}
<div class="footer">Generated by Meridian</div>
</body>
</html>`;

    const blob = new Blob([html], { type: 'text/html' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `rca-${sessionId.slice(0, 8)}-${date}.html`;
    a.click();
    window.open(url, '_blank');
    URL.revokeObjectURL(url);
  };

  return (
    <div style={{ position: 'fixed', inset: 0, background: 'rgba(0,0,0,0.8)', display: 'flex', alignItems: 'center', justifyContent: 'center', zIndex: 1000 }}>
      <div style={{ background: 'var(--bg-surface)', border: '1px solid var(--border)', borderRadius: 12, width: '90vw', maxWidth: 760, maxHeight: '88vh', display: 'flex', flexDirection: 'column' }}>

        {/* Header */}
        <div style={{ padding: '14px 20px', borderBottom: '1px solid var(--border)', display: 'flex', alignItems: 'center', gap: 10, flexShrink: 0 }}>
          <FileText size={15} style={{ color: 'var(--accent)' }} />
          <span style={{ fontWeight: 700, fontSize: 14, color: 'var(--text-primary)' }}>Root Cause Analysis Report</span>
          {loading && <span style={{ fontSize: 11, color: 'var(--accent)' }}>● Generating…</span>}
          <div style={{ marginLeft: 'auto', display: 'flex', gap: 8 }}>
            <button type="button" onClick={() => navigator.clipboard.writeText(content)} disabled={!content}
              style={{ padding: '5px 12px', background: 'transparent', border: '1px solid var(--border)', borderRadius: 5, color: 'var(--text-secondary)', fontSize: 12, cursor: content ? 'pointer' : 'not-allowed', display: 'flex', alignItems: 'center', gap: 5 }}>
              <Copy size={11} /> Copy
            </button>
            <button type="button" onClick={download} disabled={!content || loading}
              style={{ padding: '5px 12px', background: content && !loading ? 'var(--accent)' : 'var(--bg-hover)', border: 'none', borderRadius: 5, color: '#fff', fontSize: 12, cursor: content && !loading ? 'pointer' : 'not-allowed', display: 'flex', alignItems: 'center', gap: 5 }}>
              <Download size={11} /> Export PDF
            </button>
            <button type="button" onClick={onClose}
              style={{ background: 'none', border: 'none', color: 'var(--text-muted)', cursor: 'pointer', padding: '4px 6px', display: 'flex', alignItems: 'center' }}>
              <X size={14} />
            </button>
          </div>
        </div>

        {/* Body */}
        <div style={{ flex: 1, overflow: 'auto', padding: 20 }}>
          {error && (
            <p style={{ color: 'var(--error)', fontSize: 13, marginBottom: 12 }}>{error}</p>
          )}

          {!content && loading && (
            <div style={{ display: 'flex', flexDirection: 'column', gap: 10 }}>
              {[240, 160, 200, 100, 180, 140].map((w, i) => (
                <div key={i} className="skeleton" style={{ height: 14, width: w, maxWidth: '100%' }} />
              ))}
            </div>
          )}

          <textarea
            value={content}
            onChange={e => setContent(e.target.value)}
            style={{ width: '100%', minHeight: 460, background: 'var(--bg-base)', border: '1px solid var(--border)', borderRadius: 6, color: 'var(--text-primary)', fontSize: 12, padding: 14, fontFamily: 'JetBrains Mono, monospace', lineHeight: 1.7, resize: 'vertical', outline: 'none', boxSizing: 'border-box' }}
            placeholder="RCA will appear here…"
          />
        </div>

      </div>
    </div>
  );
}
