import type { GeneratedFile } from '../types';

interface DeployStage {
  id: string;
  name: string;
  status: string;
  duration?: string;
  logs: string[];
}

export const DEMO_PROMPT =
  'Create an auto-scaling group for web servers behind an ALB, with CloudWatch alarms for CPU > 70%';

export const DEMO_FILES: GeneratedFile[] = [
  {
    path: 'main.tf',
    language: 'hcl',
    content: `# main.tf — Auto Scaling Group with ALB
# Generated by InfraPilot

terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }
  }
  required_version = ">= 1.5"
}

provider "aws" {
  region = var.aws_region
}

# ─── Application Load Balancer ───────────────────────────────────────────────

resource "aws_lb" "web" {
  name               = "\${var.project_name}-alb"
  internal           = false
  load_balancer_type = "application"
  security_groups    = [aws_security_group.alb.id]
  subnets            = var.public_subnet_ids

  enable_deletion_protection = var.environment == "prod"

  tags = {
    Name        = "\${var.project_name}-alb"
    Environment = var.environment
    ManagedBy   = "InfraPilot"
  }
}

resource "aws_lb_listener" "web_http" {
  load_balancer_arn = aws_lb.web.arn
  port              = 80
  protocol          = "HTTP"

  default_action {
    type = "redirect"
    redirect {
      port        = "443"
      protocol    = "HTTPS"
      status_code = "HTTP_301"
    }
  }
}

resource "aws_lb_listener" "web_https" {
  load_balancer_arn = aws_lb.web.arn
  port              = 443
  protocol          = "HTTPS"
  ssl_policy        = "ELBSecurityPolicy-TLS13-1-2-2021-06"
  certificate_arn   = var.acm_certificate_arn

  default_action {
    type             = "forward"
    target_group_arn = aws_lb_target_group.web.arn
  }
}

resource "aws_lb_target_group" "web" {
  name        = "\${var.project_name}-tg"
  port        = 80
  protocol    = "HTTP"
  vpc_id      = var.vpc_id
  target_type = "instance"

  health_check {
    enabled             = true
    healthy_threshold   = 2
    unhealthy_threshold = 3
    interval            = 30
    path                = "/health"
    timeout             = 5
    matcher             = "200-299"
  }

  tags = {
    Environment = var.environment
    ManagedBy   = "InfraPilot"
  }
}

# ─── Security Groups ──────────────────────────────────────────────────────────

resource "aws_security_group" "alb" {
  name        = "\${var.project_name}-alb-sg"
  description = "Allow HTTP/HTTPS inbound"
  vpc_id      = var.vpc_id

  ingress {
    from_port   = 80
    to_port     = 80
    protocol    = "tcp"
    cidr_blocks = ["0.0.0.0/0"]
  }
  ingress {
    from_port   = 443
    to_port     = 443
    protocol    = "tcp"
    cidr_blocks = ["0.0.0.0/0"]
  }
  egress {
    from_port   = 0
    to_port     = 0
    protocol    = "-1"
    cidr_blocks = ["0.0.0.0/0"]
  }

  tags = { Name = "\${var.project_name}-alb-sg" }
}

resource "aws_security_group" "web" {
  name        = "\${var.project_name}-web-sg"
  description = "Allow traffic from ALB only"
  vpc_id      = var.vpc_id

  ingress {
    from_port       = 80
    to_port         = 80
    protocol        = "tcp"
    security_groups = [aws_security_group.alb.id]
  }
  egress {
    from_port   = 0
    to_port     = 0
    protocol    = "-1"
    cidr_blocks = ["0.0.0.0/0"]
  }

  tags = { Name = "\${var.project_name}-web-sg" }
}

# ─── Launch Template ─────────────────────────────────────────────────────────

resource "aws_launch_template" "web" {
  name_prefix   = "\${var.project_name}-lt-"
  image_id      = data.aws_ami.amazon_linux_2023.id
  instance_type = var.instance_type

  network_interfaces {
    associate_public_ip_address = false
    security_groups             = [aws_security_group.web.id]
  }

  user_data = base64encode(<<-EOF
    #!/bin/bash
    yum update -y
    yum install -y amazon-cloudwatch-agent
    /opt/aws/amazon-cloudwatch-agent/bin/amazon-cloudwatch-agent-ctl \\
      -a fetch-config -m ec2 -s -c ssm:\${var.cloudwatch_config_ssm_path}
  EOF
  )

  iam_instance_profile {
    name = aws_iam_instance_profile.web.name
  }

  monitoring { enabled = true }

  tag_specifications {
    resource_type = "instance"
    tags = {
      Name        = "\${var.project_name}-web"
      Environment = var.environment
    }
  }

  lifecycle { create_before_destroy = true }
}

data "aws_ami" "amazon_linux_2023" {
  most_recent = true
  owners      = ["amazon"]
  filter {
    name   = "name"
    values = ["al2023-ami-*-x86_64"]
  }
}

# ─── Auto Scaling Group ───────────────────────────────────────────────────────

resource "aws_autoscaling_group" "web" {
  name                = "\${var.project_name}-asg"
  vpc_zone_identifier = var.private_subnet_ids
  target_group_arns   = [aws_lb_target_group.web.arn]
  min_size            = var.min_capacity
  max_size            = var.max_capacity
  desired_capacity    = var.desired_capacity

  health_check_type         = "ELB"
  health_check_grace_period = 120

  launch_template {
    id      = aws_launch_template.web.id
    version = "$Latest"
  }

  instance_refresh {
    strategy = "Rolling"
    preferences {
      min_healthy_percentage = 50
    }
  }

  tag {
    key                 = "Name"
    value               = "\${var.project_name}-web"
    propagate_at_launch = true
  }
  tag {
    key                 = "Environment"
    value               = var.environment
    propagate_at_launch = true
  }
}

# ─── Auto Scaling Policies ────────────────────────────────────────────────────

resource "aws_autoscaling_policy" "scale_up" {
  name                   = "\${var.project_name}-scale-up"
  scaling_adjustment     = 2
  adjustment_type        = "ChangeInCapacity"
  cooldown               = 300
  autoscaling_group_name = aws_autoscaling_group.web.name
}

resource "aws_autoscaling_policy" "scale_down" {
  name                   = "\${var.project_name}-scale-down"
  scaling_adjustment     = -1
  adjustment_type        = "ChangeInCapacity"
  cooldown               = 300
  autoscaling_group_name = aws_autoscaling_group.web.name
}

# ─── CloudWatch Alarms ────────────────────────────────────────────────────────

resource "aws_cloudwatch_metric_alarm" "cpu_high" {
  alarm_name          = "\${var.project_name}-cpu-high"
  comparison_operator = "GreaterThanThreshold"
  evaluation_periods  = 2
  metric_name         = "CPUUtilization"
  namespace           = "AWS/EC2"
  period              = 120
  statistic           = "Average"
  threshold           = 70

  dimensions = {
    AutoScalingGroupName = aws_autoscaling_group.web.name
  }

  alarm_description = "Scale up when CPU exceeds 70% for 4 minutes"
  alarm_actions     = [aws_autoscaling_policy.scale_up.arn]

  tags = { Environment = var.environment }
}

resource "aws_cloudwatch_metric_alarm" "cpu_low" {
  alarm_name          = "\${var.project_name}-cpu-low"
  comparison_operator = "LessThanThreshold"
  evaluation_periods  = 3
  metric_name         = "CPUUtilization"
  namespace           = "AWS/EC2"
  period              = 120
  statistic           = "Average"
  threshold           = 20

  dimensions = {
    AutoScalingGroupName = aws_autoscaling_group.web.name
  }

  alarm_description = "Scale down when CPU below 20% for 6 minutes"
  alarm_actions     = [aws_autoscaling_policy.scale_down.arn]
}`,
  },
  {
    path: 'variables.tf',
    language: 'hcl',
    content: `# variables.tf

variable "project_name" {
  description = "Name prefix for all resources"
  type        = string
  default     = "myapp"

  validation {
    condition     = can(regex("^[a-z][a-z0-9-]{2,20}$", var.project_name))
    error_message = "project_name must be lowercase alphanumeric with hyphens, 3–21 chars."
  }
}

variable "aws_region" {
  description = "AWS region to deploy into"
  type        = string
  default     = "us-east-1"
}

variable "environment" {
  description = "Deployment environment"
  type        = string
  default     = "prod"

  validation {
    condition     = contains(["dev", "staging", "prod"], var.environment)
    error_message = "environment must be dev, staging, or prod."
  }
}

variable "vpc_id" {
  description = "VPC ID to deploy resources in"
  type        = string
}

variable "public_subnet_ids" {
  description = "List of public subnet IDs for the ALB"
  type        = list(string)
}

variable "private_subnet_ids" {
  description = "List of private subnet IDs for the ASG"
  type        = list(string)
}

variable "instance_type" {
  description = "EC2 instance type for web servers"
  type        = string
  default     = "t3.medium"
}

variable "min_capacity" {
  description = "Minimum number of instances in the ASG"
  type        = number
  default     = 2
}

variable "max_capacity" {
  description = "Maximum number of instances in the ASG"
  type        = number
  default     = 10
}

variable "desired_capacity" {
  description = "Desired number of instances at start"
  type        = number
  default     = 3
}

variable "acm_certificate_arn" {
  description = "ARN of the ACM certificate for HTTPS"
  type        = string
}

variable "cloudwatch_config_ssm_path" {
  description = "SSM parameter path for CloudWatch agent config"
  type        = string
  default     = "/meridian/cloudwatch-agent-config"
}`,
  },
  {
    path: 'outputs.tf',
    language: 'hcl',
    content: `# outputs.tf

output "alb_dns_name" {
  description = "DNS name of the Application Load Balancer"
  value       = aws_lb.web.dns_name
}

output "alb_zone_id" {
  description = "Hosted zone ID of the ALB (for Route 53 alias records)"
  value       = aws_lb.web.zone_id
}

output "alb_arn" {
  description = "ARN of the Application Load Balancer"
  value       = aws_lb.web.arn
}

output "target_group_arn" {
  description = "ARN of the target group"
  value       = aws_lb_target_group.web.arn
}

output "autoscaling_group_name" {
  description = "Name of the Auto Scaling Group"
  value       = aws_autoscaling_group.web.name
}

output "autoscaling_group_arn" {
  description = "ARN of the Auto Scaling Group"
  value       = aws_autoscaling_group.web.arn
}

output "web_security_group_id" {
  description = "ID of the web tier security group"
  value       = aws_security_group.web.id
}

output "alb_security_group_id" {
  description = "ID of the ALB security group"
  value       = aws_security_group.alb.id
}

output "cpu_high_alarm_arn" {
  description = "ARN of the CPU high alarm"
  value       = aws_cloudwatch_metric_alarm.cpu_high.arn
}`,
  },
  {
    path: 'README.md',
    language: 'markdown',
    content: `# Auto Scaling Group with ALB — Generated by InfraPilot

## Overview
This Terraform module provisions a production-ready auto-scaling web tier with:
- Application Load Balancer (ALB) with HTTP→HTTPS redirect
- Auto Scaling Group (ASG) with rolling instance refresh
- CloudWatch CPU alarms (scale-up at 70%, scale-down at 20%)
- Launch Template with Amazon Linux 2023
- Security groups with least-privilege rules

## Architecture

\`\`\`
Internet → [ALB :443] → [ASG: 2–10 × t3.medium]
                ↑
         CloudWatch Alarms
\`\`\`

## Prerequisites

| Resource           | Required |
|--------------------|----------|
| VPC                | ✅       |
| Public Subnets (2+)| ✅       |
| Private Subnets (2+)| ✅      |
| ACM Certificate    | ✅       |

## Usage

\`\`\`hcl
module "web_asg" {
  source = "./modules/web-asg"

  project_name       = "ecommerce"
  environment        = "prod"
  aws_region         = "us-east-1"
  vpc_id             = "vpc-0abc1234"
  public_subnet_ids  = ["subnet-0aa1", "subnet-0bb2"]
  private_subnet_ids = ["subnet-0cc3", "subnet-0dd4"]
  acm_certificate_arn = "arn:aws:acm:us-east-1:123456789012:certificate/abc-123"

  instance_type    = "t3.medium"
  min_capacity     = 2
  max_capacity     = 10
  desired_capacity = 3
}
\`\`\`

## Cost Estimate

| Resource           | $/month  |
|--------------------|----------|
| ALB               | ~$22     |
| 3× t3.medium      | ~$90     |
| CloudWatch alarms  | ~$1      |
| **Total**          | **~$113**|

## Scaling Behavior

- **Scale Up:** 2 evaluation periods × 2 min = CPU > 70% for 4 min → +2 instances
- **Scale Down:** 3 evaluation periods × 2 min = CPU < 20% for 6 min → -1 instance
- **Cooldown:** 5 minutes between scaling actions

## Security Notes

- Instances run in private subnets (no public IPs)
- ALB accepts traffic only from the internet; instances only from ALB
- CloudWatch agent is installed via user data
- Deletion protection enabled in \`prod\``,
  },
  {
    path: 'Cost Estimate',
    language: 'markdown',
    content: `# Cost Estimate — us-east-1 (Production)

> Generated by InfraPilot · Prices as of 2024

## Monthly Breakdown

| Service                    | Config                | $/hr      | $/month   |
|----------------------------|-----------------------|-----------|-----------|
| ALB                        | 1× ALB                | $0.008/hr | **$22.00**|
| ALB LCU                    | ~100 req/s            | $0.008/hr | **$8.00** |
| EC2 t3.medium (×3 desired) | 3× on-demand          | $0.042/hr | **$90.72**|
| CloudWatch Alarms          | 2 alarms              | —         | **$0.20** |
| CloudWatch Metrics         | Detailed monitoring    | —         | **$2.10** |
| Data Transfer Out          | ~100 GB/mo            | $0.09/GB  | **$9.00** |
| **Total**                  |                       |           | **$132.02**|

## Savings Opportunities

| Option                        | Savings  |
|-------------------------------|----------|
| 1-yr Reserved Instances (×3)  | -38%     |
| Spot for non-critical capacity| -70%     |
| Savings Plans (Compute)       | -32%     |

## Scaling Cost Range

| Scenario         | Instances | $/month   |
|------------------|-----------|-----------|
| Minimum (slow)   | 2×        | ~$102     |
| Desired (normal) | 3×        | ~$132     |
| Maximum (peak)   | 10×       | ~$352     |`,
  },
];

export const DEMO_DEPLOY_STAGES: DeployStage[] = [
  {
    id: 'commit',
    name: 'Git Commit',
    status: 'success',
    duration: '0.2s',
    logs: ['[00:00] Commit a3f9b12 detected', '[00:00] Author: platform-bot', '[00:00] Trigger: push to main'],
  },
  {
    id: 'plan',
    name: 'Terraform Plan',
    status: 'success',
    duration: '14.3s',
    logs: [
      '[00:01] Initializing backend...',
      '[00:03] aws_lb.web: Refreshing state...',
      '[00:09] aws_autoscaling_group.web: Refreshing state...',
      '[00:14] Plan: 12 to add, 3 to change, 0 to destroy.',
    ],
  },
  {
    id: 'approval',
    name: 'Approval Gate',
    status: 'running',
    logs: ['[00:15] Awaiting manual approval...'],
  },
  {
    id: 'apply',
    name: 'Apply',
    status: 'pending',
    logs: [],
  },
  {
    id: 'verify',
    name: 'Verify',
    status: 'pending',
    logs: [],
  },
];

export const DIAGNOSE_DEMO_LOGS = `Events:
  Type     Reason   Age                From     Message
  ----     ------   ----               ----     -------
  Normal   Pulling  3m (x4 over 12m)  kubelet  Pulling image "gcr.io/myapp/api:v2.1.0"
  Normal   Pulled   3m (x4 over 12m)  kubelet  Successfully pulled image
  Normal   Created  3m (x4 over 12m)  kubelet  Created container api
  Normal   Started  3m (x4 over 12m)  kubelet  Started container api
  Warning  BackOff  2m (x8 over 11m)  kubelet  Back-off restarting failed container

$ kubectl logs api-deployment-7d8f9b-xkq2p --previous
Error: ENOMEM: not enough memory, spawn
    at ChildProcess.spawn (internal/child_process.js:394:11)
    at Object.execFile (child_process.js:234:17)
OOMKilled: container exceeded memory limit of 256Mi`;
